backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "src/data/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "image" }
